export interface CStdSymbol {
  name: string;
  kind: 'function' | 'keyword' | 'constant' | 'type' | 'header';
  header?: string;
  signature?: string;
  description: string;
  snippet?: string;
  parameters?: { name: string; type: string; doc?: string }[];
  returnType?: string;
}

export const C_KEYWORDS: CStdSymbol[] = [
  { name: 'auto', kind: 'keyword', description: 'Especificador de classe de armazenamento automático (padrão em C).' },
  { name: 'break', kind: 'keyword', description: 'Interrompe a execução do laço atual (for, while, do) ou bloco switch.' },
  { name: 'case', kind: 'keyword', description: 'Define um rótulo de ramificação em um bloco switch.' },
  { name: 'char', kind: 'keyword', description: 'Tipo de dado primitivo de caractere (normalmente 1 byte).' },
  { name: 'const', kind: 'keyword', description: 'Qualificador de tipo que indica que o valor da variável é somente leitura.' },
  { name: 'continue', kind: 'keyword', description: 'Pula para a próxima iteração do laço atual (for, while, do).' },
  { name: 'default', kind: 'keyword', description: 'Rótulo padrão em um bloco switch quando nenhum case coincide.' },
  { name: 'do', kind: 'keyword', description: 'Inicia um laço de repetição com condição no final (do-while).' },
  { name: 'double', kind: 'keyword', description: 'Tipo numérico de ponto flutuante com precisão dupla (8 bytes).' },
  { name: 'else', kind: 'keyword', description: 'Executa um bloco de código caso a condição do if seja falsa.' },
  { name: 'enum', kind: 'keyword', description: 'Declara uma enumeração de constantes inteiras nomeadas.' },
  { name: 'extern', kind: 'keyword', description: 'Declara que uma variável ou função foi definida em outro arquivo/escopo.' },
  { name: 'float', kind: 'keyword', description: 'Tipo numérico de ponto flutuante com precisão simples (4 bytes).' },
  { name: 'for', kind: 'keyword', description: 'Estrutura de laço de repetição com inicialização, teste e incremento.' },
  { name: 'goto', kind: 'keyword', description: 'Desvia incondicionalmente o fluxo para um rótulo no mesmo escopo.' },
  { name: 'if', kind: 'keyword', description: 'Estrutura de controle condicional.' },
  { name: 'inline', kind: 'keyword', description: 'Sugere ao compilador a substituição da chamada pelo corpo da função.' },
  { name: 'int', kind: 'keyword', description: 'Tipo numérico inteiro (geralmente 4 bytes nos sistemas modernos).' },
  { name: 'long', kind: 'keyword', description: 'Modificador de tipo inteiro para expandir a capacidade de armazenamento.' },
  { name: 'register', kind: 'keyword', description: 'Sugere armazenar a variável em registrador do processador para velocidade.' },
  { name: 'return', kind: 'keyword', description: 'Retorna a execução e opcionalmente um valor a partir de uma função.' },
  { name: 'short', kind: 'keyword', description: 'Modificador de tipo para reduzir o tamanho de armazenamento do inteiro (geralmente 2 bytes).' },
  { name: 'signed', kind: 'keyword', description: 'Especifica que o tipo numérico aceita valores positivos e negativos.' },
  { name: 'sizeof', kind: 'keyword', description: 'Operador em tempo de compilação que retorna o tamanho de um tipo ou variável em bytes.' },
  { name: 'static', kind: 'keyword', description: 'Mantém o valor da variável entre chamadas ou restringe visibilidade ao arquivo.' },
  { name: 'struct', kind: 'keyword', description: 'Define uma estrutura composta por múltiplos campos heterogêneos.' },
  { name: 'switch', kind: 'keyword', description: 'Estrutura de seleção múltipla baseada em um valor inteiro/caractere.' },
  { name: 'typedef', kind: 'keyword', description: 'Cria um novo apelido/sinônimo para um tipo de dado existente.' },
  { name: 'union', kind: 'keyword', description: 'Estrutura especial cujos membros compartilham a mesma área de memória.' },
  { name: 'unsigned', kind: 'keyword', description: 'Especifica que o tipo numérico armazena apenas valores positivos (sem sinal).' },
  { name: 'void', kind: 'keyword', description: 'Indica a ausência de tipo ou que a função não retorna valor.' },
  { name: 'volatile', kind: 'keyword', description: 'Indica ao compilador que a variável pode ser alterada fora do controle do programa.' },
];

export const C_STANDARD_HEADERS: CStdSymbol[] = [
  { name: 'stdio.h', kind: 'header', description: 'Entrada e saída padrão (printf, scanf, manipulação de arquivos FILE).' },
  { name: 'stdlib.h', kind: 'header', description: 'Funções de utilidade geral (malloc, free, rand, exit, atoi, conversões).' },
  { name: 'string.h', kind: 'header', description: 'Manipulação de strings e blocos de memória (strlen, strcpy, strcmp, memset).' },
  { name: 'math.h', kind: 'header', description: 'Funções matemáticas (sqrt, pow, sin, cos, ceil, floor, round).' },
  { name: 'ctype.h', kind: 'header', description: 'Testes e conversões de caracteres (isalpha, isdigit, toupper, tolower).' },
  { name: 'stdbool.h', kind: 'header', description: 'Suporte a tipo booleano em C (bool, true, false).' },
  { name: 'time.h', kind: 'header', description: 'Manipulação de data, hora e medição de tempo de execução (time, clock).' },
  { name: 'stdint.h', kind: 'header', description: 'Tipos inteiros com larguras exatas (uint8_t, int32_t, uint64_t).' },
  { name: 'limits.h', kind: 'header', description: 'Limites mínimos e máximos dos tipos integrais (INT_MAX, INT_MIN).' },
  { name: 'assert.h', kind: 'header', description: 'Macro assert para validação e depuração de expressões lógicas.' },
  { name: 'errno.h', kind: 'header', description: 'Definição da variável errno para diagnóstico de erros do sistema.' },
];

export const C_STDLIB_SYMBOLS: CStdSymbol[] = [
  // --- stdio.h ---
  {
    name: 'printf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int printf(const char *format, ...)',
    description: 'Imprime texto formatado na saída padrão (stdout).\nExemplo: `printf("Valor: %d\\n", x);`',
    returnType: 'int',
    parameters: [
      { name: 'format', type: 'const char *', doc: 'String de formatação contendo especificadores (%d, %s, %f, etc.).' },
      { name: '...', type: 'variadic', doc: 'Argumentos correspondentes aos especificadores de formato.' },
    ],
  },
  {
    name: 'scanf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int scanf(const char *format, ...)',
    description: 'Lê dados formatados da entrada padrão (stdin) e armazena nos endereços fornecidos.\nExemplo: `scanf("%d", &x);`',
    returnType: 'int',
    parameters: [
      { name: 'format', type: 'const char *', doc: 'String de formatação com especificadores dos tipos esperados.' },
      { name: '...', type: 'variadic', doc: 'Ponteiros para as variáveis onde os dados lidos serão gravados.' },
    ],
  },
  {
    name: 'puts',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int puts(const char *str)',
    description: 'Escreve uma string na saída padrão seguida automaticamente por uma quebra de linha (\\n).',
    returnType: 'int',
    parameters: [{ name: 'str', type: 'const char *', doc: 'String terminada em nulo a ser exibida.' }],
  },
  {
    name: 'putchar',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int putchar(int character)',
    description: 'Escreve um único caractere na saída padrão.',
    returnType: 'int',
    parameters: [{ name: 'character', type: 'int', doc: 'Caractere a ser impresso.' }],
  },
  {
    name: 'getchar',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int getchar(void)',
    description: 'Lê o próximo caractere disponível da entrada padrão (stdin). Retorna EOF em caso de fim de arquivo ou erro.',
    returnType: 'int',
    parameters: [],
  },
  {
    name: 'fgets',
    kind: 'function',
    header: 'stdio.h',
    signature: 'char *fgets(char *str, int num, FILE *stream)',
    description: 'Lê com segurança uma linha de texto do fluxo de entrada especificado até num-1 caracteres.',
    returnType: 'char *',
    parameters: [
      { name: 'str', type: 'char *', doc: 'Buffer onde os caracteres lidos serão armazenados.' },
      { name: 'num', type: 'int', doc: 'Número máximo de caracteres a ler, incluindo o caractere nulo.' },
      { name: 'stream', type: 'FILE *', doc: 'Fluxo de entrada (ex: stdin ou ponteiro retornado por fopen).' },
    ],
  },
  {
    name: 'fopen',
    kind: 'function',
    header: 'stdio.h',
    signature: 'FILE *fopen(const char *filename, const char *mode)',
    description: 'Abre o arquivo especificado no modo desejado ("r", "w", "a", "rb", "wb", etc.). Retorna ponteiro FILE ou NULL.',
    returnType: 'FILE *',
    parameters: [
      { name: 'filename', type: 'const char *', doc: 'Caminho ou nome do arquivo a ser aberto.' },
      { name: 'mode', type: 'const char *', doc: 'Modo de abertura: "r" (leitura), "w" (escrita), "a" (anexo), etc.' },
    ],
  },
  {
    name: 'fclose',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int fclose(FILE *stream)',
    description: 'Fecha o arquivo associado ao fluxo e descarrega todos os buffers pendentes. Retorna 0 em caso de sucesso.',
    returnType: 'int',
    parameters: [{ name: 'stream', type: 'FILE *', doc: 'Ponteiro para a estrutura FILE a ser fechada.' }],
  },
  {
    name: 'fprintf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int fprintf(FILE *stream, const char *format, ...)',
    description: 'Escreve texto formatado no fluxo de arquivo especificado (ex: stderr ou arquivo aberto).',
    returnType: 'int',
    parameters: [
      { name: 'stream', type: 'FILE *', doc: 'Destino da escrita (stdout, stderr ou arquivo).' },
      { name: 'format', type: 'const char *', doc: 'String de formatação.' },
      { name: '...', type: 'variadic', doc: 'Valores a formatar.' },
    ],
  },
  {
    name: 'fscanf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int fscanf(FILE *stream, const char *format, ...)',
    description: 'Lê dados formatados a partir do fluxo de arquivo especificado.',
    returnType: 'int',
    parameters: [
      { name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo de onde ler.' },
      { name: 'format', type: 'const char *', doc: 'String de formatação.' },
      { name: '...', type: 'variadic', doc: 'Ponteiros para armazenar os dados.' },
    ],
  },
  {
    name: 'sprintf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int sprintf(char *str, const char *format, ...)',
    description: 'Escreve texto formatado diretamente em uma string de destino na memória.',
    returnType: 'int',
    parameters: [
      { name: 'str', type: 'char *', doc: 'Buffer de destino.' },
      { name: 'format', type: 'const char *', doc: 'String de formatação.' },
      { name: '...', type: 'variadic', doc: 'Valores a formatar.' },
    ],
  },
  {
    name: 'snprintf',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int snprintf(char *str, size_t size, const char *format, ...)',
    description: 'Versão segura de sprintf que respeita o limite máximo de bytes do buffer para evitar estouro de memória.',
    returnType: 'int',
    parameters: [
      { name: 'str', type: 'char *', doc: 'Buffer de destino.' },
      { name: 'size', type: 'size_t', doc: 'Tamanho máximo do buffer em bytes.' },
      { name: 'format', type: 'const char *', doc: 'String de formatação.' },
      { name: '...', type: 'variadic', doc: 'Valores a formatar.' },
    ],
  },
  {
    name: 'perror',
    kind: 'function',
    header: 'stdio.h',
    signature: 'void perror(const char *str)',
    description: 'Imprime em stderr uma mensagem personalizada seguida da descrição do último erro ocorrido (errno).',
    returnType: 'void',
    parameters: [{ name: 'str', type: 'const char *', doc: 'Prefixo descritivo impresso antes da mensagem de erro.' }],
  },
  {
    name: 'fread',
    kind: 'function',
    header: 'stdio.h',
    signature: 'size_t fread(void *ptr, size_t size, size_t count, FILE *stream)',
    description: 'Lê count elementos, cada um com tamanho size bytes, do fluxo para o bloco de memória apontado por ptr.',
    returnType: 'size_t',
    parameters: [
      { name: 'ptr', type: 'void *', doc: 'Buffer de destino.' },
      { name: 'size', type: 'size_t', doc: 'Tamanho de cada elemento em bytes.' },
      { name: 'count', type: 'size_t', doc: 'Quantidade de elementos.' },
      { name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo.' },
    ],
  },
  {
    name: 'fwrite',
    kind: 'function',
    header: 'stdio.h',
    signature: 'size_t fwrite(const void *ptr, size_t size, size_t count, FILE *stream)',
    description: 'Escreve dados binários da memória para o arquivo.',
    returnType: 'size_t',
    parameters: [
      { name: 'ptr', type: 'const void *', doc: 'Ponteiro para os dados a serem gravados.' },
      { name: 'size', type: 'size_t', doc: 'Tamanho de cada elemento em bytes.' },
      { name: 'count', type: 'size_t', doc: 'Quantidade de elementos.' },
      { name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo de destino.' },
    ],
  },
  {
    name: 'fseek',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int fseek(FILE *stream, long int offset, int origin)',
    description: 'Move a posição do ponteiro interno de leitura/escrita do arquivo (SEEK_SET, SEEK_CUR, SEEK_END).',
    returnType: 'int',
    parameters: [
      { name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo.' },
      { name: 'offset', type: 'long int', doc: 'Deslocamento em bytes em relação à origem.' },
      { name: 'origin', type: 'int', doc: 'Ponto de referência: SEEK_SET (início), SEEK_CUR (atual), SEEK_END (fim).' },
    ],
  },
  {
    name: 'ftell',
    kind: 'function',
    header: 'stdio.h',
    signature: 'long int ftell(FILE *stream)',
    description: 'Retorna a posição atual do ponteiro do arquivo em bytes desde o início.',
    returnType: 'long int',
    parameters: [{ name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo.' }],
  },
  {
    name: 'rewind',
    kind: 'function',
    header: 'stdio.h',
    signature: 'void rewind(FILE *stream)',
    description: 'Reposiciona o ponteiro do arquivo de volta ao início.',
    returnType: 'void',
    parameters: [{ name: 'stream', type: 'FILE *', doc: 'Fluxo de arquivo.' }],
  },
  {
    name: 'remove',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int remove(const char *filename)',
    description: 'Exclui o arquivo indicado do sistema de arquivos.',
    returnType: 'int',
    parameters: [{ name: 'filename', type: 'const char *', doc: 'Nome/caminho do arquivo a remover.' }],
  },
  {
    name: 'rename',
    kind: 'function',
    header: 'stdio.h',
    signature: 'int rename(const char *oldname, const char *newname)',
    description: 'Renomeia ou move um arquivo no sistema de arquivos.',
    returnType: 'int',
    parameters: [
      { name: 'oldname', type: 'const char *', doc: 'Nome atual.' },
      { name: 'newname', type: 'const char *', doc: 'Novo nome desejado.' },
    ],
  },
  { name: 'FILE', kind: 'type', header: 'stdio.h', description: 'Estrutura que armazena informações sobre um fluxo de arquivo aberto.' },
  { name: 'stdin', kind: 'constant', header: 'stdio.h', description: 'Fluxo padrão de entrada (teclado / terminal).' },
  { name: 'stdout', kind: 'constant', header: 'stdio.h', description: 'Fluxo padrão de saída (tela / terminal).' },
  { name: 'stderr', kind: 'constant', header: 'stdio.h', description: 'Fluxo padrão de mensagens de erro.' },
  { name: 'EOF', kind: 'constant', header: 'stdio.h', description: 'Constante inteira negativa que indica o Fim de Arquivo (End Of File).' },
  { name: 'NULL', kind: 'constant', header: 'stdio.h', description: 'Ponteiro nulo ((void *)0).' },
  { name: 'SEEK_SET', kind: 'constant', header: 'stdio.h', description: 'Origem para fseek: início do arquivo.' },
  { name: 'SEEK_CUR', kind: 'constant', header: 'stdio.h', description: 'Origem para fseek: posição atual no arquivo.' },
  { name: 'SEEK_END', kind: 'constant', header: 'stdio.h', description: 'Origem para fseek: final do arquivo.' },

  // --- stdlib.h ---
  {
    name: 'malloc',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void *malloc(size_t size)',
    description: 'Aloca dinamicamente um bloco contínuo de bytes na heap sem inicializar o conteúdo.\nExemplo: `int *vet = malloc(10 * sizeof(int));`',
    returnType: 'void *',
    parameters: [{ name: 'size', type: 'size_t', doc: 'Quantidade de bytes a alocar.' }],
  },
  {
    name: 'calloc',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void *calloc(size_t num, size_t size)',
    description: 'Aloca dinamicamente espaço para num elementos de size bytes cada e zera todos os bytes na memória.',
    returnType: 'void *',
    parameters: [
      { name: 'num', type: 'size_t', doc: 'Número de elementos.' },
      { name: 'size', type: 'size_t', doc: 'Tamanho de cada elemento em bytes.' },
    ],
  },
  {
    name: 'realloc',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void *realloc(void *ptr, size_t new_size)',
    description: 'Redimensiona um bloco de memória previamente alocado por malloc ou calloc.',
    returnType: 'void *',
    parameters: [
      { name: 'ptr', type: 'void *', doc: 'Ponteiro para o bloco de memória existente.' },
      { name: 'new_size', type: 'size_t', doc: 'Novo tamanho desejado em bytes.' },
    ],
  },
  {
    name: 'free',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void free(void *ptr)',
    description: 'Libera a memória alocada dinamicamente na heap apontada por ptr para evitar vazamento de memória (memory leak).',
    returnType: 'void',
    parameters: [{ name: 'ptr', type: 'void *', doc: 'Ponteiro retornado por malloc, calloc ou realloc.' }],
  },
  {
    name: 'exit',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void exit(int status)',
    description: 'Termina imediatamente a execução do programa e retorna o código de status fornecido ao sistema operacional.',
    returnType: 'void',
    parameters: [{ name: 'status', type: 'int', doc: 'Código de encerramento (0 ou EXIT_SUCCESS para sucesso).' }],
  },
  {
    name: 'atoi',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'int atoi(const char *str)',
    description: 'Converte uma string numérica em um valor inteiro (int).\nExemplo: `int n = atoi("123");`',
    returnType: 'int',
    parameters: [{ name: 'str', type: 'const char *', doc: 'String a ser convertida em int.' }],
  },
  {
    name: 'atof',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'double atof(const char *str)',
    description: 'Converte uma string numérica em um valor de ponto flutuante de precisão dupla (double).',
    returnType: 'double',
    parameters: [{ name: 'str', type: 'const char *', doc: 'String a ser convertida.' }],
  },
  {
    name: 'atol',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'long int atol(const char *str)',
    description: 'Converte uma string numérica em um valor inteiro longo (long int).',
    returnType: 'long int',
    parameters: [{ name: 'str', type: 'const char *', doc: 'String a ser convertida.' }],
  },
  {
    name: 'rand',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'int rand(void)',
    description: 'Gera um número inteiro pseudoaleatório no intervalo entre 0 e RAND_MAX.',
    returnType: 'int',
    parameters: [],
  },
  {
    name: 'srand',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void srand(unsigned int seed)',
    description: 'Inicializa a semente para o gerador de números pseudoaleatórios rand().\nExemplo: `srand(time(NULL));`',
    returnType: 'void',
    parameters: [{ name: 'seed', type: 'unsigned int', doc: 'Semente numérica inicial.' }],
  },
  {
    name: 'qsort',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'void qsort(void *base, size_t num, size_t size, int (*compar)(const void *, const void *))',
    description: 'Ordena um vetor de elementos usando o algoritmo Quicksort e uma função de comparação fornecida.',
    returnType: 'void',
    parameters: [
      { name: 'base', type: 'void *', doc: 'Ponteiro para o início do vetor.' },
      { name: 'num', type: 'size_t', doc: 'Número de elementos no vetor.' },
      { name: 'size', type: 'size_t', doc: 'Tamanho em bytes de cada elemento.' },
      { name: 'compar', type: 'int (*)(const void *, const void *)', doc: 'Ponteiro para a função comparadora.' },
    ],
  },
  {
    name: 'abs',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'int abs(int n)',
    description: 'Retorna o valor absoluto (positivo) de um número inteiro.',
    returnType: 'int',
    parameters: [{ name: 'n', type: 'int', doc: 'Número inteiro.' }],
  },
  {
    name: 'system',
    kind: 'function',
    header: 'stdlib.h',
    signature: 'int system(const char *command)',
    description: 'Executa um comando no shell / ambiente do sistema operacional.',
    returnType: 'int',
    parameters: [{ name: 'command', type: 'const char *', doc: 'String com o comando a executar.' }],
  },
  { name: 'RAND_MAX', kind: 'constant', header: 'stdlib.h', description: 'Valor inteiro máximo que pode ser retornado pela função rand().' },
  { name: 'EXIT_SUCCESS', kind: 'constant', header: 'stdlib.h', description: 'Código padrão de saída para finalização com sucesso de programa (0).' },
  { name: 'EXIT_FAILURE', kind: 'constant', header: 'stdlib.h', description: 'Código padrão de saída indicando erro na finalização do programa (1).' },

  // --- string.h ---
  {
    name: 'strlen',
    kind: 'function',
    header: 'string.h',
    signature: 'size_t strlen(const char *str)',
    description: 'Calcula o comprimento da string até o caractere terminador nulo (\\0), sem contá-lo.',
    returnType: 'size_t',
    parameters: [{ name: 'str', type: 'const char *', doc: 'String terminada em nulo.' }],
  },
  {
    name: 'strcpy',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strcpy(char *dest, const char *src)',
    description: 'Copia a string apontada por src para o buffer dest (incluindo o terminador \\0).',
    returnType: 'char *',
    parameters: [
      { name: 'dest', type: 'char *', doc: 'Buffer de destino que receberá a cópia.' },
      { name: 'src', type: 'const char *', doc: 'String de origem a ser copiada.' },
    ],
  },
  {
    name: 'strncpy',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strncpy(char *dest, const char *src, size_t n)',
    description: 'Copia até no máximo n caracteres da string src para o destino dest.',
    returnType: 'char *',
    parameters: [
      { name: 'dest', type: 'char *', doc: 'Buffer de destino.' },
      { name: 'src', type: 'const char *', doc: 'String de origem.' },
      { name: 'n', type: 'size_t', doc: 'Número máximo de caracteres a copiar.' },
    ],
  },
  {
    name: 'strcat',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strcat(char *dest, const char *src)',
    description: 'Concatena a string src ao final da string dest.',
    returnType: 'char *',
    parameters: [
      { name: 'dest', type: 'char *', doc: 'String de destino que receberá a concatenação.' },
      { name: 'src', type: 'const char *', doc: 'String de origem adicionada ao final.' },
    ],
  },
  {
    name: 'strncat',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strncat(char *dest, const char *src, size_t n)',
    description: 'Concatena até no máximo n caracteres de src ao final de dest.',
    returnType: 'char *',
    parameters: [
      { name: 'dest', type: 'char *', doc: 'String de destino.' },
      { name: 'src', type: 'const char *', doc: 'String de origem.' },
      { name: 'n', type: 'size_t', doc: 'Número máximo de caracteres.' },
    ],
  },
  {
    name: 'strcmp',
    kind: 'function',
    header: 'string.h',
    signature: 'int strcmp(const char *str1, const char *str2)',
    description: 'Compara lexicograficamente duas strings. Retorna 0 se forem idênticas, < 0 se str1 < str2, e > 0 se str1 > str2.',
    returnType: 'int',
    parameters: [
      { name: 'str1', type: 'const char *', doc: 'Primeira string.' },
      { name: 'str2', type: 'const char *', doc: 'Segunda string.' },
    ],
  },
  {
    name: 'strncmp',
    kind: 'function',
    header: 'string.h',
    signature: 'int strncmp(const char *str1, const char *str2, size_t n)',
    description: 'Compara até os primeiros n caracteres de duas strings.',
    returnType: 'int',
    parameters: [
      { name: 'str1', type: 'const char *', doc: 'Primeira string.' },
      { name: 'str2', type: 'const char *', doc: 'Segunda string.' },
      { name: 'n', type: 'size_t', doc: 'Número máximo de caracteres a comparar.' },
    ],
  },
  {
    name: 'strchr',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strchr(const char *str, int c)',
    description: 'Localiza a primeira ocorrência do caractere c na string str.',
    returnType: 'char *',
    parameters: [
      { name: 'str', type: 'const char *', doc: 'String a pesquisar.' },
      { name: 'c', type: 'int', doc: 'Caractere a localizar.' },
    ],
  },
  {
    name: 'strstr',
    kind: 'function',
    header: 'string.h',
    signature: 'char *strstr(const char *haystack, const char *needle)',
    description: 'Localiza a primeira ocorrência da substring needle dentro da string haystack.',
    returnType: 'char *',
    parameters: [
      { name: 'haystack', type: 'const char *', doc: 'Texto principal.' },
      { name: 'needle', type: 'const char *', doc: 'Substring a procurar.' },
    ],
  },
  {
    name: 'memset',
    kind: 'function',
    header: 'string.h',
    signature: 'void *memset(void *ptr, int value, size_t num)',
    description: 'Preenche os primeiros num bytes do bloco de memória ptr com o valor especificado.\nExemplo: `memset(vet, 0, sizeof(vet));`',
    returnType: 'void *',
    parameters: [
      { name: 'ptr', type: 'void *', doc: 'Ponteiro para o bloco de memória.' },
      { name: 'value', type: 'int', doc: 'Valor byte a ser copiado (convertido para unsigned char).' },
      { name: 'num', type: 'size_t', doc: 'Número de bytes a preencher.' },
    ],
  },
  {
    name: 'memcpy',
    kind: 'function',
    header: 'string.h',
    signature: 'void *memcpy(void *dest, const void *src, size_t n)',
    description: 'Copia n bytes da área de memória src para dest. As áreas não devem se sobrepor.',
    returnType: 'void *',
    parameters: [
      { name: 'dest', type: 'void *', doc: 'Destino da cópia de memória.' },
      { name: 'src', type: 'const void *', doc: 'Origem da memória.' },
      { name: 'n', type: 'size_t', doc: 'Número de bytes a copiar.' },
    ],
  },
  {
    name: 'memmove',
    kind: 'function',
    header: 'string.h',
    signature: 'void *memmove(void *dest, const void *src, size_t n)',
    description: 'Copia n bytes da memória de forma segura mesmo que as áreas de origem e destino se sobreponham.',
    returnType: 'void *',
    parameters: [
      { name: 'dest', type: 'void *', doc: 'Destino.' },
      { name: 'src', type: 'const void *', doc: 'Origem.' },
      { name: 'n', type: 'size_t', doc: 'Bytes a copiar.' },
    ],
  },
  {
    name: 'memcmp',
    kind: 'function',
    header: 'string.h',
    signature: 'int memcmp(const void *ptr1, const void *ptr2, size_t n)',
    description: 'Compara os primeiros n bytes de duas regiões de memória.',
    returnType: 'int',
    parameters: [
      { name: 'ptr1', type: 'const void *', doc: 'Primeiro bloco de memória.' },
      { name: 'ptr2', type: 'const void *', doc: 'Segundo bloco de memória.' },
      { name: 'n', type: 'size_t', doc: 'Número de bytes a comparar.' },
    ],
  },
  { name: 'size_t', kind: 'type', header: 'string.h', description: 'Tipo inteiro sem sinal retornado pelo operador sizeof e funções de tamanho.' },

  // --- math.h ---
  {
    name: 'sqrt',
    kind: 'function',
    header: 'math.h',
    signature: 'double sqrt(double x)',
    description: 'Calcula e retorna a raiz quadrada de x.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor numérico não negativo.' }],
  },
  {
    name: 'pow',
    kind: 'function',
    header: 'math.h',
    signature: 'double pow(double base, double exponent)',
    description: 'Calcula a potência: base elevada ao expoente.',
    returnType: 'double',
    parameters: [
      { name: 'base', type: 'double', doc: 'Valor base.' },
      { name: 'exponent', type: 'double', doc: 'Valor do expoente.' },
    ],
  },
  {
    name: 'sin',
    kind: 'function',
    header: 'math.h',
    signature: 'double sin(double x)',
    description: 'Calcula o seno de um ângulo x fornecido em radianos.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Ângulo em radianos.' }],
  },
  {
    name: 'cos',
    kind: 'function',
    header: 'math.h',
    signature: 'double cos(double x)',
    description: 'Calcula o cosseno de um ângulo x em radianos.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Ângulo em radianos.' }],
  },
  {
    name: 'tan',
    kind: 'function',
    header: 'math.h',
    signature: 'double tan(double x)',
    description: 'Calcula a tangente de um ângulo x em radianos.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Ângulo em radianos.' }],
  },
  {
    name: 'ceil',
    kind: 'function',
    header: 'math.h',
    signature: 'double ceil(double x)',
    description: 'Arredonda x para cima até o menor inteiro maior ou igual a x.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor a arredondar.' }],
  },
  {
    name: 'floor',
    kind: 'function',
    header: 'math.h',
    signature: 'double floor(double x)',
    description: 'Arredonda x para baixo até o maior inteiro menor ou igual a x.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor a arredondar.' }],
  },
  {
    name: 'round',
    kind: 'function',
    header: 'math.h',
    signature: 'double round(double x)',
    description: 'Arredonda x para o inteiro mais próximo.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor a arredondar.' }],
  },
  {
    name: 'fabs',
    kind: 'function',
    header: 'math.h',
    signature: 'double fabs(double x)',
    description: 'Retorna o valor absoluto (positivo) de um número de ponto flutuante.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor flutuante.' }],
  },
  {
    name: 'log',
    kind: 'function',
    header: 'math.h',
    signature: 'double log(double x)',
    description: 'Calcula o logaritmo natural (base e) de x.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor positivo.' }],
  },
  {
    name: 'log10',
    kind: 'function',
    header: 'math.h',
    signature: 'double log10(double x)',
    description: 'Calcula o logaritmo na base 10 de x.',
    returnType: 'double',
    parameters: [{ name: 'x', type: 'double', doc: 'Valor positivo.' }],
  },

  // --- ctype.h ---
  {
    name: 'isalpha',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int isalpha(int c)',
    description: 'Verifica se o caractere c é uma letra do alfabeto (A-Z ou a-z).',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a verificar.' }],
  },
  {
    name: 'isdigit',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int isdigit(int c)',
    description: 'Verifica se o caractere c é um dígito decimal (0-9).',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a verificar.' }],
  },
  {
    name: 'isalnum',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int isalnum(int c)',
    description: 'Verifica se o caractere c é alfanumérico (letra ou número).',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a verificar.' }],
  },
  {
    name: 'isspace',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int isspace(int c)',
    description: 'Verifica se o caractere c é de espaço em branco (espaço, tabulação, quebra de linha).',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a verificar.' }],
  },
  {
    name: 'toupper',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int toupper(int c)',
    description: 'Converte uma letra minúscula para maiúscula correspondente.',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a converter.' }],
  },
  {
    name: 'tolower',
    kind: 'function',
    header: 'ctype.h',
    signature: 'int tolower(int c)',
    description: 'Converte uma letra maiúscula para minúscula correspondente.',
    returnType: 'int',
    parameters: [{ name: 'c', type: 'int', doc: 'Caractere a converter.' }],
  },

  // --- stdbool.h ---
  { name: 'bool', kind: 'type', header: 'stdbool.h', description: 'Tipo booleano definido em C99 (armazena true ou false).' },
  { name: 'true', kind: 'constant', header: 'stdbool.h', description: 'Constante booleana de valor verdadeiro (1).' },
  { name: 'false', kind: 'constant', header: 'stdbool.h', description: 'Constante booleana de valor falso (0).' },

  // --- time.h ---
  {
    name: 'time',
    kind: 'function',
    header: 'time.h',
    signature: 'time_t time(time_t *timer)',
    description: 'Retorna a hora atual do calendário como um valor time_t (segundos desde 1 de janeiro de 1970).',
    returnType: 'time_t',
    parameters: [{ name: 'timer', type: 'time_t *', doc: 'Ponteiro opcional para armazenar o tempo, ou NULL.' }],
  },
  {
    name: 'clock',
    kind: 'function',
    header: 'time.h',
    signature: 'clock_t clock(void)',
    description: 'Retorna o tempo de processamento consumido pelo programa em pulsos de clock (dividir por CLOCKS_PER_SEC para segundos).',
    returnType: 'clock_t',
    parameters: [],
  },
  { name: 'time_t', kind: 'type', header: 'time.h', description: 'Tipo aritmético utilizado para representar tempos no calendário.' },
  { name: 'clock_t', kind: 'type', header: 'time.h', description: 'Tipo aritmético capaz de representar o tempo de processamento.' },
  { name: 'CLOCKS_PER_SEC', kind: 'constant', header: 'time.h', description: 'Número de pulsos de clock por segundo da função clock().' },

  // --- stdint.h ---
  { name: 'int8_t', kind: 'type', header: 'stdint.h', description: 'Inteiro com sinal exatamente de 8 bits (-128 a 127).' },
  { name: 'int16_t', kind: 'type', header: 'stdint.h', description: 'Inteiro com sinal de 16 bits (-32768 a 32767).' },
  { name: 'int32_t', kind: 'type', header: 'stdint.h', description: 'Inteiro com sinal de 32 bits (-2147483648 a 2147483647).' },
  { name: 'int64_t', kind: 'type', header: 'stdint.h', description: 'Inteiro com sinal de 64 bits.' },
  { name: 'uint8_t', kind: 'type', header: 'stdint.h', description: 'Inteiro sem sinal de 8 bits (0 a 255).' },
  { name: 'uint16_t', kind: 'type', header: 'stdint.h', description: 'Inteiro sem sinal de 16 bits (0 a 65535).' },
  { name: 'uint32_t', kind: 'type', header: 'stdint.h', description: 'Inteiro sem sinal de 32 bits (0 a 4294967295).' },
  { name: 'uint64_t', kind: 'type', header: 'stdint.h', description: 'Inteiro sem sinal de 64 bits.' },

  // --- limits.h ---
  { name: 'INT_MAX', kind: 'constant', header: 'limits.h', description: 'Valor máximo representável por uma variável int (+2147483647 em sistemas de 32/64 bits).' },
  { name: 'INT_MIN', kind: 'constant', header: 'limits.h', description: 'Valor mínimo representável por uma variável int (-2147483648 em sistemas de 32/64 bits).' },
  { name: 'CHAR_MAX', kind: 'constant', header: 'limits.h', description: 'Valor máximo de char.' },
  { name: 'CHAR_MIN', kind: 'constant', header: 'limits.h', description: 'Valor mínimo de char.' },
];
